# This workflow does the following job:
# Installs the repo and runs all tests using pytest.
# Analyses code with pylint

name: build-and-test

on: [push]

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.12
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[tests]
      - name: Analysing the code with pylint
        run: |
          python -m pylint --fail-under=10 `find -regextype egrep -regex '(.*.py)$'` |
          tee pylint.txt
      - name: Test with pytest
        run: |
          pytest tests --rootdir=tests
